---
dist: focal
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-software-properties
      - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: ansible_container
    - MOLECULE_DISTRO: coglinev3/python
  matrix:
    - MOLECULE_DISTRO_VERSION: alpine-3.9
    - MOLECULE_DISTRO_VERSION: alpine-3.10
    - MOLECULE_DISTRO_VERSION: alpine-3.11
    - MOLECULE_DISTRO_VERSION: alpine-3.12
    - MOLECULE_DISTRO_VERSION: centos-6
    - MOLECULE_DISTRO_VERSION: centos-7
    - MOLECULE_DISTRO_VERSION: centos-8
    - MOLECULE_DISTRO_VERSION: debian-8
    - MOLECULE_DISTRO_VERSION: debian-9
    - MOLECULE_DISTRO_VERSION: debian-10
    - MOLECULE_DISTRO_VERSION: fedora-31
    - MOLECULE_DISTRO_VERSION: fedora-32
    - MOLECULE_DISTRO_VERSION: ubuntu-16.04
    - MOLECULE_DISTRO_VERSION: ubuntu-18.04
    - MOLECULE_DISTRO_VERSION: ubuntu-20.04

install:
  # Install test dependencies.
  - pip3 install -U jinja2 requests ansible molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}

script:
  # Run tests.
  - molecule test

jobs:
  include:
    - stage: trigger container-ansible
      if: branch = master
      install: skip
      before_script: skip
      script: bash .travis/trigger-job $(dirname $TRAVIS_REPO_SLUG) container-ansible

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
