---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible_container
    - AUTHOR_NAME: coglinev3
  matrix:
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 7
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: coglinev3/python
      MOLECULE_DISTRO_VERSION: ubuntu-16.04
    - MOLECULE_DISTRO: coglinev3/python
      MOLECULE_DISTRO_VERSION: ubuntu-18.04
install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-${ROLE_NAME} ${AUTHOR_NAME}.${ROLE_NAME}
  - cd ${AUTHOR_NAME}.${ROLE_NAME}

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
