---
# file: roles/ansible_container/tasks/setup-RedHat.yml

- block:
  - name: Delete unit files which might cause issues 1/2
    become: "{{ ansible_container_become }}"
    shell: for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done
    args:
      executable: /bin/bash
      chdir: /lib/systemd/system/sysinit.target.wants
    register: result

  - name: Delete unit files which might cause issues 2/2
    become: "{{ ansible_container_become }}"
    command: "rm -f {{ item }}"
    args:
      warn: false
    with_items:
      - "/lib/systemd/system/multi-user.target.wants/*"
      - "/etc/systemd/system/*.wants/*"
      - "/lib/systemd/system/local-fs.target.wants/*"
      - "/lib/systemd/system/sockets.target.wants/*udev*"
      - "/lib/systemd/system/sockets.target.wants/*initctl*"
      - "/lib/systemd/system/basic.target.wants/*"
      - "/lib/systemd/system/anaconda.target.wants/*"
  when: ansible_distribution_major_version > "6"

- name: "RHEL: Install EPEL Repository"
  become: "{{ ansible_container_become }}"
  yum:
    name: epel-release
    state: present
    update_cache: "yes"
  when: not ansible_distribution == "Fedora"
  tags:
    - install

- name: Install requirements
  become: "{{ ansible_container_become }}"
  yum:
    name: "{{ ansible_container_requirements }}"
    state: present
    update_cache: "yes"

- name: Upgrade all packages
  become: "{{ ansible_container_become }}"
  yum:
    name: '*'
    state: latest
    update_cache: "yes"

- name: Clear package cache
  become: "{{ ansible_container_become }}"
  command: yum clean all
  args:
    warn: false

- name: Check for /lib/systemd/system directory
  stat:
    path: /lib/systemd/system
  register: systemd_dir

# Remove unnecessary getty and udev targets that result in high CPU usage when
# using multiple containers with Molecule
# (https://github.com/ansible/molecule/issues/1104)
- name: Remove unnecessary getty and udev targets
  become: "{{ ansible_container_become }}"
  command: "rm -f {{ item }}"
  args:
    warn: false
  with_items:
    - "/lib/systemd/system/systemd*udev*"
    - "/lib/systemd/system/getty.target"
  when: systemd_dir.stat.isdir is defined and systemd_dir.stat.isdir

- name: Check for /etc/rc.d/rc.sysinit
  stat:
    path: /etc/rc.d/rc.sysinit
  register: sysinit_file

- block:
    # Remove unnecessary getty and udev services that can result in high CPU usage
    # when using multiple containers with Molecule
    # (https://github.com/ansible/molecule/issues/1104)
    - name: "Comment out start_udev"
      lineinfile:
        path: /etc/rc.d/rc.sysinit
        regexp: '^(.*)start_udev'
        line: '#\1start_udev'
        backrefs: "yes"
        backup: "yes"
        owner: root
        group: root
        mode: 0755

    - name: "Remove unnecessary tty's"
      become: "{{ ansible_container_become }}"
      command: "rm -f /etc/init/tty.conf"
      args:
        warn: false
  when: sysinit_file.stat.isreg is defined and sysinit_file.stat.isreg
