---
# file: roles/ansible_container/tasks/setup-Debian.yml

- name: "Debian: Update all packages to the latest version"
  become: "{{ ansible_container_become }}"
  apt:
    upgrade: dist

- name: Install requirements
  become: "{{ ansible_container_become }}"
  apt:
    name: "{{ ansible_container_requirements }}"
    state: present
    update_cache: "yes"

- name: Remove apt history
  become: "{{ ansible_container_become }}"
  command: rm -f /var/log/apt/history.log
  changed_when: false
  args:
    warn: false
  when: ansible_container_build_dependencies is defined

- name: Install Ansible build dependencies
  become: "{{ ansible_container_become }}"
  apt:
    name: "{{ ansible_container_build_dependencies }}"
    state: present
    update_cache: "yes"
  notify: remove apt_build_dependencies
  when: ansible_container_build_dependencies is defined

- name: Remove repository cache
  become: "{{ ansible_container_become }}"
  command: rm -rf /var/lib/apt/lists/*
  changed_when: false
  args:
    warn: false

- name: Check for /lib/systemd/system directory
  stat:
    path: /lib/systemd/system
  register: systemd_dir

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)
- name: Remove unnecessary getty and udev targets
  become: "{{ ansible_container_become }}"
  command: "rm -f {{ item }}"
  args:
    warn: false
  with_items:
    - "/lib/systemd/system/systemd*udev*"
    - "/lib/systemd/system/getty.target"
  when: systemd_dir.stat.isdir is defined and systemd_dir.stat.isdir

- name: Get python version
  script: get-python-version
  register: python_version

- name: Extract python major version
  set_fact:
    python_major_version: "{{ python_version.stdout.split('.')[0] }}"

- name: "Upgrade pip to version < 21.0.0"
  become: "{{ ansible_container_become }}"
  pip:
    name:
      - 'pip<21.0.0'
    state: latest
  when:
    python_major_version|int == 2
    or python_version.stdout <= "3.6.0"

- name: Install pip requirements
  become: "{{ ansible_container_become }}"
  pip:
    name:
      - markupsafe
      - 'setuptools<45.0.0'
    state: latest
  when:
    python_major_version|int == 2
    or python_version.stdout <= "3.6.0"
