---
# file: roles/ansible_container/tasks/setup-Debian.yml

# Bypass a Ubuntu 18.04 Bug:
# systemd : Depends: libsystemd0 (= 237-3ubuntu10.53) but 237-3ubuntu10.54 is to be installed.
- name: "Debian: Install libsystemd0 version 237-3ubuntu10.53"
  become: "{{ ansible_container_become }}"
  ansible.builtin.apt:
    name: "libsystemd0=237-3ubuntu10.53"
    force: true
    state: present
    update_cache: "yes"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"

- name: "Debian: Update all packages to the latest version"
  become: "{{ ansible_container_become }}"
  ansible.builtin.apt:
    upgrade: dist

- name: Install requirements
  become: "{{ ansible_container_become }}"
  ansible.builtin.apt:
    name: "{{ ansible_container_requirements }}"
    state: present
    update_cache: "yes"

- name: Remove apt history
  become: "{{ ansible_container_become }}"
  ansible.builtin.file:
    path: /var/log/apt/history.log
    state: absent
  changed_when: false
  when: ansible_container_build_dependencies is defined

- name: Install Ansible build dependencies
  become: "{{ ansible_container_become }}"
  ansible.builtin.apt:
    name: "{{ ansible_container_build_dependencies }}"
    state: present
    update_cache: "yes"
  notify: remove apt_build_dependencies
  when: ansible_container_build_dependencies is defined

- name: Remove repository cache
  become: "{{ ansible_container_become }}"
  ansible.builtin.command: rm -rf /var/lib/apt/lists/*
  changed_when: false

- name: Check for /lib/systemd/system directory
  ansible.builtin.stat:
    path: /lib/systemd/system
  register: systemd_dir

# Remove unnecessary getty and udev targets that result in high CPU usage when
# using multiple containers with Molecule
# (https://github.com/ansible/molecule/issues/1104)
- name: Remove unnecessary getty and udev targets
  become: "{{ ansible_container_become }}"
  ansible.builtin.command: "rm -f {{ item }}"
  with_items:
    - "/lib/systemd/system/systemd*udev*"
    - "/lib/systemd/system/getty.target"
  when: systemd_dir.stat.isdir is defined and systemd_dir.stat.isdir
