---
# file: roles/ansible_container/tasks/setup-ansible.yml

- name: Install Ansible via Pip
  become: "{{ ansible_container_become }}"
  pip:
    name: ansible
    state: "{{ ansible_container_package_state }}"
  environment:
    LC_ALL: "C.UTF-8"
