---
# file: roles/ansible_container/tasks/setup-ansible.yml

- name: Get python version
  script: get-python-version
  register: python_version

- name: Show Python version string
  debug:
    var: python_version

- name: Extract python major version
  set_fact:
    python_major_version: "{{ python_version.stdout.split('.')[0] }}"

- name: Extract python minor version
  set_fact:
    python_minor_version: "{{ python_version.stdout.split('.')[1] }}"

- name: "Upgrade pip and ansible requierements for old python 2.7 or 3.5"
  block:
    - name: "Python2: Upgrade pip to version < 21.0.0"
      become: "{{ ansible_container_become }}"
      pip:
        name:
          - 'pip<21.0.0'
        state: latest

    - name: "Python2: Install ansible requirements"
      become: "{{ ansible_container_become }}"
      pip:
        name:
          - 'setuptools<45.0.0'
          - markupsafe
          - paramiko
        state: latest
  when:
    python_major_version|int == 2
    or ( python_major_version|int == 3 and
    python_minor_version|int < 6 )

- name: "Upgrade pip and ansible requierements for python >= 3.6"
  block:
    - name: "Python3: Upgrade pip to the latest version "
      become: "{{ ansible_container_become }}"
      pip:
        name:
          - pip
        state: latest

    - name: "Python3: Install ansible requirements"
      become: "{{ ansible_container_become }}"
      pip:
        name:
          - 'cryptography<3.4'
          - markupsafe
          - paramiko
        state: latest
  when:
    - python_major_version|int == 3
    - python_minor_version|int >= 6

- name: Install Ansible via Pip
  become: "{{ ansible_container_become }}"
  pip:
    name: ansible
    state: "{{ ansible_container_package_state }}"
  environment:
    LC_ALL: "C.UTF-8"
