---
# file: roles/ansible_container/handlesr/main.yml

- name: Cleanup apk_build_dependencies
  become: "{{ ansible_container_become }}"
  community.general.apk:
    name: build-dependencies
    state: absent

- name: Update sshd
  become: "{{ ansible_container_become }}"
  command: rc-update add sshd
  args:
    warn: false

- name: Get installed build dependencies
  become: "{{ ansible_container_become }}"
  shell: >
    cat /var/log/apt/history.log
    | grep Install
    | grep -v python-minimal
    | sed -e "s/^Install://"
    | sed -e "s/:\([^)]*),\?\)/\n/g"
  args:
    warn: false
  register: build_deps
  listen: remove apt_build_dependencies
  when:
    not (ansible_distribution == "Debian"
    and ansible_distribution_major_version == "8")

- name: Uninstall build dependencies
  become: "{{ ansible_container_become }}"
  apt:
    name: "{{ build_deps.stdout_lines }}"
    state: absent
  listen: remove apt_build_dependencies
  when:
    not (ansible_distribution == "Debian"
    and ansible_distribution_major_version == "8")
