---
# file: roles/ansible_container/handlesr/main.yml

- name: cleanup apk_build_dependencies
  become: "{{ ansible_container_become }}"
  apk:
    name: build-dependencies
    state: absent

- name: rc_update sshd
  become: "{{ ansible_container_become }}"
  command: rc-update add sshd
  args:
    warn: false

- name: Get installed build dependencies
  become: "{{ ansible_container_become }}"
  shell: 'cat /var/log/apt/history.log | grep Install | grep -v python-minimal | sed -e "s/^Install://" | sed -e "s/:\([^)]*),\?\)/\n/g"'
  args:
    warn: false
  register: build_deps
  listen: remove apt_build_dependencies

- name: Uninstall build dependencies
  become: "{{ ansible_container_become }}"
  apt:
    name: "{{ build_deps.stdout_lines }}"
    state: absent
  listen: remove apt_build_dependencies
