---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible_container"
      ansible.builtin.include_role:
        name: "coglinev3.ansible_container"
      vars:
        ansible_container_become: false
        ansible_container_install_type: pip
