---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Detect OS."
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: "Check if user ansible exists."
      ansible.builtin.getent:
        database: passwd
        key: ansible
        fail_key: true

    - name: "Get Ansible version."
      remote_user: ansible
      ansible.builtin.shell: "PATH=~/.local/bin:${PATH} ansible --version"
      register: local_ansible_version
      changed_when: false
      failed_when: false

    - name: "Check Ansible version."
      ansible.builtin.assert:
        that:
          - local_ansible_version.rc == 0
        fail_msg: "Ansible not installed properly"
        success_msg: "{{ local_ansible_version.stdout_lines[0] }} installed correctly"
