---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible_container"
      include_role:
        name: "coglinev3.ansible_container"
      vars:
        ansible_container_become: false

    - name: "Log in as User ansible and execute ansible --version"
      remote_user: root
      become: true
      become_user: ansible
      shell: PATH=/usr/local/bin:/bin:/usr/bin ansible --version
      register: ansible_version

    - name: Check Ansible version
      assert:
        that:
          - ansible_version.major == 2
        fail_msg: "Ansible not installed properly"
        success_msg: "Ansible {{ ansible_version.string }} installed correctly"
