---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible_container"
      include_role:
        name: "coglinev3.ansible_container"
      vars:
        ansible_container_become: false
