---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/${MOLECULE_DISTRO:-coglinev3/python}:${MOLECULE_DISTRO_VERSION:-alpine-3.18}
    pre_build_image: true
    command: tail -f /dev/null
provisioner:
  name: ansible
  log: false
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
