---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_REGISTRY:-docker.io}/${MOLECULE_NAMESPACE:-library}/${MOLECULE_DISTRO:-alpine}:${MOLECULE_DISTRO_VERSION:-3.22}
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    cgroupns_mode: host
    privileged: true
    command: tail -f /dev/null
provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      roles_path: ~/.ansible/roles
  env:
    ANSIBLE_ROLES_PATH: ~/.ansible/roles
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
