---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check if ansible exists."
      remote_user: ansible
      ansible.builtin.shell: "PATH=~/.local/bin:${PATH} ansible --version"
      register: local_ansible_version
      changed_when: false
      failed_when: false

    - name: Debug
      ansible.builtin.debug:
        var: local_ansible_version

    - name: "Check Ansible version."
      ansible.builtin.assert:
        that:
          - local_ansible_version.rc == 0
        fail_msg: "Ansible not installed properly"
        success_msg: "{{ local_ansible_version.stdout_lines[0] }} installed correctly"

    - name: "Detect OS."
      when: local_ansible_version.rc == 0
      block:
        - name: "Gather facts."
          ansible.builtin.setup:
        - name: "Print OS."
          ansible.builtin.debug:
            msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"
