---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Log in as User ansible and execute ansible --version"
      become: true
      become_user: ansible
      ansible.builtin.command: ansible --version
      environment:
        PATH: /usr/local/bin:/bin:/usr/bin
      register: local_ansible_version
      changed_when: local_ansible_version.rc != 0
      failed_when: local_ansible_version.rc != 0

    - name: Show ansible_version
      ansible.builtin.debug:
        var: local_ansible_version

    - name: Check Ansible version
      ansible.builtin.assert:
        that:
          - ansible_version.major == 2
        fail_msg: "Ansible not installed properly"
        success_msg: "Ansible {{ ansible_version.string }} installed correctly"

    - name: Show OS
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"
