#!/usr/bin/env bash

version_string=
if [[ -e /usr/libexec/platform-python ]]; then
  version_string=$(/usr/libexec/platform-python --version  2>&1 | grep -v platform-python)
else
  version_string=$(python3 --version 2> /dev/null || python --version 2>&1)
fi

# print version number
echo ${version_string} | cut -d ' ' -f 2

exit 0
